# Generated by Django 5.0.4 on 2024-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0002_alter_purchase_order_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='po_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
