# Generated by Django 5.0.4 on 2024-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0003_alter_purchase_order_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
